# Generated by Django 4.2.23 on 2025-08-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Two-Factor Auth',
                'verbose_name_plural': 'Two-Factor Auth',
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twofactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='twofactor.usertwofactor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usertwofactor',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_user_twofactor_per_user'),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['twofactor', 'code', 'used'], name='twofactor_b_twofact_7bc30d_idx'),
        ),
    ]
