# Generated by Django 4.2.23 on 2025-09-08 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_salt_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='last_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user'], name='accounts_lo_user_id_2a8aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['locked_until'], name='accounts_lo_locked__89470e_idx'),
        ),
    ]
